### 1. Login as Owner to Central Admin Panel
POST http://localhost/api/central/v1/login
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "email": "owner@saas.com",
    "password": "password"
}

> {%
    client.global.set("central_token", response.body.token);
%}


### 2. Logout from Central Admin Panel
POST http://localhost/api/v1/logout
Accept: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{central_token}}


### 3. Login as Owner to company_a (Tenant space via shadow copy)
POST http://localhost/api/login
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost

{
    "email": "owner@saas.com",
    "password": "password"
}

> {%
    client.global.set("auth_token", response.body.token);
%}


### 4. Login as Manager Sub Account to company_a
POST http://localhost/api/login
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost

{
    "email": "manager@companya.com",
    "password": "password"
}

> {%
    client.global.set("auth_token", response.body.token);
%}


### 5a. Login as a Viewer Sub Account to company_a
POST http://localhost/api/login
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost

{
    "email": "viewer@companya.com",
    "password": "password"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### 5b. Login as a Accountant Sub Account to company_a
POST http://localhost/api/login
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost

{
    "email": "accountant@companya.com",
    "password": "password"
}

> {%
    client.global.set("auth_token", response.body.token);
%}


### 6. Logout from company_a
POST http://localhost/api/logout
Accept: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}


### 7. Test Role Protection company_a
GET http://localhost/api/test-role-protection
Accept: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}


### 8. Create Invoice company_a (Advanced with multiple EU VAT line items in EUR)
POST http://localhost/api/invoices
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}

{
    "invoice_number": "INV-EU-2026-{{$random.integer(1, 99999)}}",
    "customer_name": "Acme Europe Logistics BV",
    "customer_vat_number": "NL847294729B01",
    "due_date": "2026-10-14",
    "items": [
        {
            "description": "Enterprise SaaS Server Hardware Node (Local EU Warehouse Delivery)",
            "quantity": 1,
            "unit_net_price": 2500.00,
            "vat_rate_id": 1
        },
        {
            "description": "Cloud Infrastructure Licensing & Cross-Border Consultation (Reverse Charge)",
            "quantity": 12,
            "unit_net_price": 150.00,
            "vat_rate_id": 3
        }
    ]
}

> {%
    // Capture the newly created invoice ID for downstream detailed resource tests
    client.global.set("invoice_id", response.body.data.id);
%}


### 9. Get Invoice list company_a
GET http://localhost/api/invoices
Accept: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}


### 10. Get Single Invoice Details company_a
GET http://localhost/api/invoices/{{invoice_id}}
Accept: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}


### 11. Update Invoice company_a (Advanced multi-item sync in EUR)
PUT http://localhost/api/invoices/{{invoice_id}}
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}

{
    "customer_name": "Acme Europe Logistics BV - Modified",
    "items": [
        {
            "description": "Enterprise SaaS Server Hardware Node (Local EU Warehouse Delivery)",
            "quantity": 1,
            "unit_net_price": 2500.00,
            "vat_rate_id": 1
        },
        {
            "description": "Extended EU SLA Technical Support (New Line Added)",
            "quantity": 1,
            "unit_net_price": 400.00,
            "vat_rate_id": 1
        }
    ]
}



### 12. Delete Invoice company_a
DELETE http://localhost/api/invoices/{{invoice_id}}
Accept: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}


### 13. Create Invitation company_a (Team Management)
POST http://localhost/api/invitations
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost
Authorization: Bearer {{auth_token}}

{
    "email": "new.employee@companya.com",
    "role": "accountant"
}

> {%
    // Extract the secure token string out of the generated activation URL dynamically
    var url = response.body.data.activation_url;
    var token = url.split('token=')[1];
    client.global.set("invitation_token", token);
%}

### 14. Accept Invitation & Register Account company_a
POST http://localhost/api/register/accept
Accept: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Host: company_a.localhost

{
    "token": "{{invitation_token}}",
    "name": "Mark Accountant Created Via API",
    "password": "password",
    "password_confirmation": "password"
}

